# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 7_shifts_python_sdk import schemas  # noqa: F401


class RolesCreateRoleRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "color",
            "department_id",
            "name",
            "location_id",
        }
        
        class properties:
            name = schemas.StrSchema
            color = schemas.StrSchema
            location_id = schemas.IntSchema
            department_id = schemas.IntSchema
            
            
            class sort(
                schemas.IntSchema
            ):
                pass
            job_code = schemas.StrSchema
        
            @staticmethod
            def stations() -> typing.Type['RolesCreateRoleRequestStations']:
                return RolesCreateRoleRequestStations
            __annotations__ = {
                "name": name,
                "color": color,
                "location_id": location_id,
                "department_id": department_id,
                "sort": sort,
                "job_code": job_code,
                "stations": stations,
            }
    
    color: MetaOapg.properties.color
    department_id: MetaOapg.properties.department_id
    name: MetaOapg.properties.name
    location_id: MetaOapg.properties.location_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["location_id"]) -> MetaOapg.properties.location_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["department_id"]) -> MetaOapg.properties.department_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sort"]) -> MetaOapg.properties.sort: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["job_code"]) -> MetaOapg.properties.job_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stations"]) -> 'RolesCreateRoleRequestStations': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "color", "location_id", "department_id", "sort", "job_code", "stations", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["location_id"]) -> MetaOapg.properties.location_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["department_id"]) -> MetaOapg.properties.department_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sort"]) -> typing.Union[MetaOapg.properties.sort, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["job_code"]) -> typing.Union[MetaOapg.properties.job_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stations"]) -> typing.Union['RolesCreateRoleRequestStations', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "color", "location_id", "department_id", "sort", "job_code", "stations", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        color: typing.Union[MetaOapg.properties.color, str, ],
        department_id: typing.Union[MetaOapg.properties.department_id, decimal.Decimal, int, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        location_id: typing.Union[MetaOapg.properties.location_id, decimal.Decimal, int, ],
        sort: typing.Union[MetaOapg.properties.sort, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        job_code: typing.Union[MetaOapg.properties.job_code, str, schemas.Unset] = schemas.unset,
        stations: typing.Union['RolesCreateRoleRequestStations', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RolesCreateRoleRequest':
        return super().__new__(
            cls,
            *args,
            color=color,
            department_id=department_id,
            name=name,
            location_id=location_id,
            sort=sort,
            job_code=job_code,
            stations=stations,
            _configuration=_configuration,
            **kwargs,
        )

from 7_shifts_python_sdk.model.roles_create_role_request_stations import RolesCreateRoleRequestStations
