# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from 7_shifts_python_sdk import schemas  # noqa: F401


class TimeOffUpdateTimeOffByIdRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            user_id = schemas.IntSchema
            from_date = schemas.StrSchema
            to_date = schemas.StrSchema
            partial = schemas.BoolSchema
            
            
            class partial_from(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'partial_from':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class partial_to(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'partial_to':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            comments = schemas.StrSchema
            status = schemas.IntSchema
            status_action_message = schemas.StrSchema
            category = schemas.StrSchema
        
            @staticmethod
            def hours() -> typing.Type['TimeOffUpdateTimeOffByIdRequestHours']:
                return TimeOffUpdateTimeOffByIdRequestHours
            __annotations__ = {
                "user_id": user_id,
                "from_date": from_date,
                "to_date": to_date,
                "partial": partial,
                "partial_from": partial_from,
                "partial_to": partial_to,
                "comments": comments,
                "status": status,
                "status_action_message": status_action_message,
                "category": category,
                "hours": hours,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_id"]) -> MetaOapg.properties.user_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["from_date"]) -> MetaOapg.properties.from_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["to_date"]) -> MetaOapg.properties.to_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["partial"]) -> MetaOapg.properties.partial: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["partial_from"]) -> MetaOapg.properties.partial_from: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["partial_to"]) -> MetaOapg.properties.partial_to: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["comments"]) -> MetaOapg.properties.comments: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status_action_message"]) -> MetaOapg.properties.status_action_message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["category"]) -> MetaOapg.properties.category: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hours"]) -> 'TimeOffUpdateTimeOffByIdRequestHours': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["user_id", "from_date", "to_date", "partial", "partial_from", "partial_to", "comments", "status", "status_action_message", "category", "hours", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_id"]) -> typing.Union[MetaOapg.properties.user_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["from_date"]) -> typing.Union[MetaOapg.properties.from_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["to_date"]) -> typing.Union[MetaOapg.properties.to_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["partial"]) -> typing.Union[MetaOapg.properties.partial, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["partial_from"]) -> typing.Union[MetaOapg.properties.partial_from, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["partial_to"]) -> typing.Union[MetaOapg.properties.partial_to, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["comments"]) -> typing.Union[MetaOapg.properties.comments, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status_action_message"]) -> typing.Union[MetaOapg.properties.status_action_message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["category"]) -> typing.Union[MetaOapg.properties.category, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hours"]) -> typing.Union['TimeOffUpdateTimeOffByIdRequestHours', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["user_id", "from_date", "to_date", "partial", "partial_from", "partial_to", "comments", "status", "status_action_message", "category", "hours", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        user_id: typing.Union[MetaOapg.properties.user_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        from_date: typing.Union[MetaOapg.properties.from_date, str, schemas.Unset] = schemas.unset,
        to_date: typing.Union[MetaOapg.properties.to_date, str, schemas.Unset] = schemas.unset,
        partial: typing.Union[MetaOapg.properties.partial, bool, schemas.Unset] = schemas.unset,
        partial_from: typing.Union[MetaOapg.properties.partial_from, None, str, schemas.Unset] = schemas.unset,
        partial_to: typing.Union[MetaOapg.properties.partial_to, None, str, schemas.Unset] = schemas.unset,
        comments: typing.Union[MetaOapg.properties.comments, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        status_action_message: typing.Union[MetaOapg.properties.status_action_message, str, schemas.Unset] = schemas.unset,
        category: typing.Union[MetaOapg.properties.category, str, schemas.Unset] = schemas.unset,
        hours: typing.Union['TimeOffUpdateTimeOffByIdRequestHours', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TimeOffUpdateTimeOffByIdRequest':
        return super().__new__(
            cls,
            *args,
            user_id=user_id,
            from_date=from_date,
            to_date=to_date,
            partial=partial,
            partial_from=partial_from,
            partial_to=partial_to,
            comments=comments,
            status=status,
            status_action_message=status_action_message,
            category=category,
            hours=hours,
            _configuration=_configuration,
            **kwargs,
        )

from 7_shifts_python_sdk.model.time_off_update_time_off_by_id_request_hours import TimeOffUpdateTimeOffByIdRequestHours
