# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_department_assignments.post import CreateDepartmentAssignment
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_location_assignments.post import CreateLocationAssignment
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_role_assignments.post import CreateRoleAssignment
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_role_assignments_role_id.delete import DeleteRoleAssignment
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_assignments.get import List
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_department_assignments.get import ListDepartmentAssignments
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_location_assignments.get import ListLocationAssignments
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_role_assignments.get import ListRoleAssignments
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_department_assignments_department_id.delete import RemoveDepartmentAssignment
from 7_shifts_python_sdk.paths.v2_company_company_id_users_user_id_location_assignments_location_id.delete import RemoveLocationAssignment
from 7_shifts_python_sdk.apis.tags.user_assignments_api_raw import UserAssignmentsApiRaw


class UserAssignmentsApi(
    CreateDepartmentAssignment,
    CreateLocationAssignment,
    CreateRoleAssignment,
    DeleteRoleAssignment,
    List,
    ListDepartmentAssignments,
    ListLocationAssignments,
    ListRoleAssignments,
    RemoveDepartmentAssignment,
    RemoveLocationAssignment,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UserAssignmentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UserAssignmentsApiRaw(api_client)
