# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

import unittest

import 7_shifts_python_sdk
from 7_shifts_python_sdk.model.external_user_mappings_update_mapping_by_identifier_response import ExternalUserMappingsUpdateMappingByIdentifierResponse
from 7_shifts_python_sdk import configuration


class TestExternalUserMappingsUpdateMappingByIdentifierResponse(unittest.TestCase):
    """ExternalUserMappingsUpdateMappingByIdentifierResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
