# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredReportsGetWorkedHoursWagesResponseUsersItemRolesItemTotal(TypedDict):
    # Regular hours
    regular_hours: typing.Union[int, float]

    # Regular pay
    regular_pay: typing.Union[int, float]

    # Overtime hours
    overtime_hours: typing.Union[int, float]

    # Overtime pay
    overtime_pay: typing.Union[int, float]

    # Holiday hours
    holiday_hours: typing.Union[int, float]

    # Holiday pay
    holiday_pay: typing.Union[int, float]

    # Compliance exceptions pay
    compliance_exceptions_pay: typing.Union[int, float]

    # Total hours
    total_hours: typing.Union[int, float]

    # Total pay
    total_pay: typing.Union[int, float]

    # Tips declared by employee through 7punches
    total_tips: typing.Union[int, float]

    # Cash tips
    cash_tips: typing.Union[int, float]

    # Credit card tips
    credit_card_tips: typing.Union[int, float]

    # Total payment tips
    total_payment_tips: typing.Union[int, float]

    # Declared tips either from 7punches or POS
    declared_tips: typing.Union[int, float]

    # Autogratuity
    auto_gratuity: typing.Union[int, float]

    # Withheld CC amount
    withheld_cc_amount: typing.Union[int, float]

    # Tip in amount
    tip_in: typing.Union[int, float]

    # Tip out amount
    tip_out: typing.Union[int, float]

    # Earned Tips
    earned_tips: typing.Union[int, float]

class OptionalReportsGetWorkedHoursWagesResponseUsersItemRolesItemTotal(TypedDict, total=False):
    # Premium / Double overtime hours
    premium_overtime_hours: typing.Union[int, float]

    # Daily + Weekly + Consecutive overtime hours
    non_premium_overtime_hours: typing.Union[int, float]

    # Premium / Double overtime pay
    premium_overtime_pay: typing.Union[int, float]

    # Daily + Weekly + Consecutive overtime pay
    non_premium_overtime_pay: typing.Union[int, float]

    # Declared tips from POS
    pos_declared_tips: typing.Union[int, float]

class ReportsGetWorkedHoursWagesResponseUsersItemRolesItemTotal(RequiredReportsGetWorkedHoursWagesResponseUsersItemRolesItemTotal, OptionalReportsGetWorkedHoursWagesResponseUsersItemRolesItemTotal):
    pass
