# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTipPoolGetManualEntryTipsResponseDataItem(TypedDict):
    # UUID for the associated Tip Pool
    tip_pool_settings_uuid: str

    # The date of the manually entered tips
    entry_date: str

    # The tip amount for the given manual entry
    tip_amount: typing.Union[int, float]

class OptionalTipPoolGetManualEntryTipsResponseDataItem(TypedDict, total=False):
    # Manual Entry UUID
    uuid: typing.Optional[str]

    # UUID for the associated Day Part (if any)
    day_part_uuid: typing.Optional[str]

    # When this manual entry record was created
    created: str

    # When this manual entry record was last modified
    modified: str

class TipPoolGetManualEntryTipsResponseDataItem(RequiredTipPoolGetManualEntryTipsResponseDataItem, OptionalTipPoolGetManualEntryTipsResponseDataItem):
    pass
