# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from 7_shifts_python_sdk.type.tip_pool_get_settings_response_data_item_day_part_uuids import TipPoolGetSettingsResponseDataItemDayPartUuids
from 7_shifts_python_sdk.type.tip_pool_get_settings_response_data_item_tip_pool_cadence_settings import TipPoolGetSettingsResponseDataItemTipPoolCadenceSettings
from 7_shifts_python_sdk.type.tip_pool_get_settings_response_data_item_tip_pool_contributions import TipPoolGetSettingsResponseDataItemTipPoolContributions
from 7_shifts_python_sdk.type.tip_pool_get_settings_response_data_item_tip_pool_stakeholders import TipPoolGetSettingsResponseDataItemTipPoolStakeholders
from 7_shifts_python_sdk.type.tip_pool_get_settings_response_data_item_unmapped_contribution_filters import TipPoolGetSettingsResponseDataItemUnmappedContributionFilters

class RequiredTipPoolGetSettingsResponseDataItem(TypedDict):
    # Company ID
    company_id: int

    # Location ID
    location_id: int

    # Tip pool contribution type
    contribution_type: str

    # Tip pool distribution type
    distribution_type: str

    # The proportion of sales tips or tips for unassigned roles (in percentage) you wish to contribute to the tip pool
    sales_tip_percentage: typing.Optional[typing.Union[int, float]]

    # Tip pool name
    name: str

    # Whether the tip pool is enabled
    enabled: bool

    tip_pool_stakeholders: TipPoolGetSettingsResponseDataItemTipPoolStakeholders

    tip_pool_contributions: TipPoolGetSettingsResponseDataItemTipPoolContributions

class OptionalTipPoolGetSettingsResponseDataItem(TypedDict, total=False):
    # Tip pool settings UUID
    uuid: typing.Optional[str]

    day_part_uuids: typing.Optional[TipPoolGetSettingsResponseDataItemDayPartUuids]

    # A field representing whether we source our unmapped contribution amounts from tips, sales receipts or remaining tips
    unmapped_contribution_method: typing.Optional[str]

    unmapped_contribution_filters: TipPoolGetSettingsResponseDataItemUnmappedContributionFilters

    tip_pool_cadence_settings: typing.Optional[TipPoolGetSettingsResponseDataItemTipPoolCadenceSettings]

    # When this tip pool was created in UTC timezone and Zulu format
    created: datetime

    # When this tip pool was last modified in UTC timezone and Zulu format
    modified: datetime

class TipPoolGetSettingsResponseDataItem(RequiredTipPoolGetSettingsResponseDataItem, OptionalTipPoolGetSettingsResponseDataItem):
    pass
