# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AuthenticationGenerateOAuthTokenRequest(BaseModel):
    # Token grant type. For Partner OAuth tokens specifying client_credentials
    grant_type: Literal["client_credentials", "password", "authorization_code", "refresh_token"] = Field(alias='grant_type')

    client_id: str = Field(alias='client_id')

    client_secret: typing.Optional[str] = Field(None, alias='client_secret')

    # A space-delimited list of scopes.
    scope: typing.Optional[str] = Field(None, alias='scope')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
