# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ReportsGetDailyStatsResponseDataSummary(BaseModel):
    # The current actual sales in cents
    current_actual_sales: typing.Optional[int] = Field(None, alias='current_actual_sales')

    # The current projected sales in cents
    current_projected_sales: typing.Optional[int] = Field(None, alias='current_projected_sales')

    # The past actual sales in cents
    past_actual_sales: typing.Optional[int] = Field(None, alias='past_actual_sales')

    # The past projected sales in cents
    past_projected_sales: typing.Optional[int] = Field(None, alias='past_projected_sales')

    # The current actual labor in cents
    current_actual_labor: typing.Optional[int] = Field(None, alias='current_actual_labor')

    # The current projected labor in cents
    current_projected_labor: typing.Optional[int] = Field(None, alias='current_projected_labor')

    # The past actual labor in cents
    past_actual_labor: typing.Optional[int] = Field(None, alias='past_actual_labor')

    # The current labor ratio
    current_labor_ratio: typing.Optional[typing.Union[int, float]] = Field(None, alias='current_labor_ratio')

    # The current labor target
    current_labor_target: typing.Optional[typing.Union[int, float]] = Field(None, alias='current_labor_target')

    # The current labor ratio
    past_labor_ratio: typing.Optional[typing.Union[int, float]] = Field(None, alias='past_labor_ratio')

    # The current sales per man hour
    current_spmh: typing.Optional[typing.Union[int, float]] = Field(None, alias='current_spmh')

    # The past sales per man hour
    past_spmh: typing.Optional[typing.Union[int, float]] = Field(None, alias='past_spmh')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
