# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from 7_shifts_python_sdk.pydantic.reports_get_worked_hours_wages_response_total import ReportsGetWorkedHoursWagesResponseTotal
from 7_shifts_python_sdk.pydantic.reports_get_worked_hours_wages_response_users import ReportsGetWorkedHoursWagesResponseUsers

class ReportsGetWorkedHoursWagesResponse(BaseModel):
    users: ReportsGetWorkedHoursWagesResponseUsers = Field(alias='users')

    # Whether compliance exceptions and their costs should be shown
    show_exception_costs: bool = Field(alias='show_exception_costs')

    # Whether tips from integrations should be shown
    tip_tracking_enabled: bool = Field(alias='tip_tracking_enabled')

    # Whether we should render the tips column
    show_tips: bool = Field(alias='show_tips')

    total: ReportsGetWorkedHoursWagesResponseTotal = Field(alias='total')

    # Start date of report date range
    start: date = Field(alias='start')

    # End date of report date range
    end: date = Field(alias='end')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
