# coding: utf-8

"""
    7shifts API

    7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.

    The version of the OpenAPI document: 2023-05-01
    Contact: api-support@7shifts.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from 7_shifts_python_sdk.pydantic.roles_get_role_response_data_stations import RolesGetRoleResponseDataStations

class RolesGetRoleResponseData(BaseModel):
    # Role ID
    id: typing.Optional[int] = Field(None, alias='id')

    # Company ID
    company_id: typing.Optional[int] = Field(None, alias='company_id')

    # Location ID
    location_id: typing.Optional[int] = Field(None, alias='location_id')

    # Department ID
    department_id: typing.Optional[int] = Field(None, alias='department_id')

    # A hex number representing the color
    color: typing.Optional[typing.Optional[str]] = Field(None, alias='color')

    # The number of stations this role contains
    num_stations: typing.Optional[int] = Field(None, alias='num_stations')

    # Role name
    name: typing.Optional[str] = Field(None, alias='name')

    # Job code
    job_code: typing.Optional[typing.Optional[str]] = Field(None, alias='job_code')

    # The order in which the roles will be listed in the web app
    sort: typing.Optional[typing.Optional[int]] = Field(None, alias='sort')

    stations: typing.Optional[RolesGetRoleResponseDataStations] = Field(None, alias='stations')

    # The ISO8601 date and time in UTC when the role was created
    created: typing.Optional[typing.Optional[datetime]] = Field(None, alias='created')

    # The ISO8601 date and time in UTC when the role was modified
    modified: typing.Optional[typing.Optional[datetime]] = Field(None, alias='modified')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
